server:
  port: 8080
#eureka config#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:1111/eureka/
    instance:
      appname: ly-eureka-server
spring:
  application:
    name: rw_server
