server:
  port: 8080

#eureka config#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8080/eureka/
    instance:
      appname: ly-eureka-server
#spring config#
spring:
  application:
    name: rw_server
